import streamlit as st
import random

st.title("Most Likely To... Random Question Generator")

questions = [
    "Who is most likely to marry someone rich and famous?",
    "Who is most likely to flirt their way out of trouble?",
    "Who is most likely to go skinny dipping?",
    "Who is most likely to date more than one person at a time?",
    "Who is most likely to kiss and tell?",
    "Who is most likely to sneak into a concert or event without a ticket?",
    "Who is most likely to pee in the shower?",
    "Who is most likely to get arrested?",
    "Who is most likely to die first in a horror film?",
    "Who is most likely to expose receipts during an argument?",
    "Who is most likely to kiss someone at a party just for attention?",
    "Who is most likely to be on the news for being involved with a scam?",
    "Who is most likely to go a week without a shower?",
    "Who is most likely to go through someone’s phone without permission?",
    "Who is most likely to end up in a news headline?",
    "Who is most likely to hook up with their ex again?",
    "Who is most likely to tattle on someone?",
    "Who is most likely to never change their sheets?",
    "Who is most likely to send their food back at a restaurant?",
    "Who is most likely to fall in love with their best friend?",
    "Who is most likely to get into a love triangle?",
    "Who is most likely to go on a date just for free food?",
    "Who is most likely to end up dating someone way older?",
    "Who is most likely to lead someone on just for the attention?",
    "Who is most likely to start dating someone new a week after a breakup?",
    "Who is most likely to quit a job on the spot after one bad day?",
    "Who is most likely to stir up drama at a family holiday dinner?",
    "Who is most likely to drop a “you won’t believe what I heard” the second they walk in the room?",
    "Who is most likely to fake being sick to get out of plans?",
    "Who is most likely to say “I’m over it” and then bring it up again a week late",
    "Who is most likely to block someone with little provocation?",
    "Who is most likely to keep a secret until it’s convenient to spill?",
    "Who is most likely to post a breakup TikTok within 24 hours?",
    "Who is most likely to pretend they didn’t see a message but actually did?",
    "Who is most likely to screenshot a conversation “just in case”?",
    "Who is most likely to post a cryptic message and refuse to explain it?",
    "Who is most likely to take karaoke way too seriously?",
    "Who is most likely to pull a dramatic stunt just because they’re bored?",
    "Who is most likely to take the longest getting ready and still be late?",
    "Who is most likely to start dating someone just to make someone else jealous?",
    "Who is most likely to live abroad?",
    "Who is most likely to compete on Survivor (and actually win)?",
    "Who is most likely to turn their life into a reality TV show?",
    "Who is most likely to give the best advice?",
    "Who is most likely to write fanfic that secretly blows up online?",
    "Who is most likely to go viral for a hot take?",
    "Who is most likely to start a business?",
    "Who is most likely to win a costume contest with zero prep time?",
    "Who is most likely to have their own Netflix stand-up special?",
    "Who is most likely to survive a zombie apocalypse?",
    "Who is most likely to become an anarchist?",
    "Who is most likely to move into a lighthouse just for the aesthetic?",
    "Who is most likely to host a travel show?",
    "Who is most likely to live off the grid and raise goats?",
    "Who is most likely to change their name and move to Central America?",
    "Who is most likely to join the circus and love it?",
    "Who is most likely to disappear for a year and come back with a mysterious tattoo?",
    "Who is most likely to join a pirate crew if it was still an option?",
    "Who is most likely to decide they’re a prophet and start a movement?",
    "Who is most likely to fake their own death and watch their funeral?",
    "Who is most likely to join a Renaissance fair full-time?"
]

if st.button("Generate Random Question"):
    random_question = random.choice(questions)
    st.markdown(f"**{random_question}**")